---
# tasks file for roles/git

- name: Add aliases to ~/.gitconfig
  community.general.git_config:
    name: "alias.{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: 'co', value: 'checkout' }
    - { name: 'cob', value: 'checkout -b' }
    - { name: 'pfl', value: 'push --force-with-lease' }
    - { name: 'a', value: 'commit --amend --no-edit' }
    - { name: 'l', value: 'log --oneline' }
    - { name: 'm', value: 'checkout main' }
