---
# tasks file for roles/git

- name: 'Add aliases to ~/.gitconfig'
  community.general.git_config:
    name: 'alias.{{ item.name }}'
    scope: 'global'
    value: '{{ item.value }}'
  loop:
    - { name: 'a', value: 'commit --amend --no-edit' }
    - { name: 'co', value: 'checkout' }
    - { name: 'cob', value: 'checkout -b' }
    - { name: 'l', value: 'log --all --decorate --graph --oneline --pretty=format:''%C(auto)%h%Creset -%C(auto)%d%Creset %s%Creset - %C(auto)%cn %Cgreen(%cr)%Creset'' -10' }
    - { name: 'm', value: 'checkout main' }
    - { name: 'pfl', value: 'push --force-with-lease' }
    - { name: 'aliases', value: 'config --get-regexp ''^alias\.''' }
